### Crear un nuevo post


POST http://localhost:3000/posts
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NTllZDdkMDU5NGUxMTVhZGE2YThhMmQiLCJpc0FkbWluIjpmYWxzZSwiaWF0IjoxNzA0OTA4OTIzLCJleHAiOjE3MDQ5MTI1MjN9._7WjeexeaBnmdc6y_Q-UJIXy-cw3Q3oXlsk5YuQmQoo

{
  "title": "La paz de Flerken durmiendo",
  "content": "Después de un día lleno de travesuras, Flerken finalmente se ha dormido. Es sorprendente ver lo tranquilo y adorable que puede ser, recogido en una pequeña bola de pelo gris en su cama. Estos momentos de calma son realmente especiales.",
  "categories": [
    "relaxation",
    "cute",
    "animals"
  ]
}








### Obtener todos los posts con paginación

GET http://localhost:3000/posts?limit=20

### Obtener un post por id

GET http://localhost:3000/posts/658dc74e74722faf97232caa

### Actualizar un post por id

PATCH http://localhost:3000/posts/658de124c4efa6c2272858a7
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkFkbWluIiwic3ViIjoiNjU4ZDlhMTA3NjRiZDljNTg2MWMxNTZmIiwiaXNBZG1pbiI6dHJ1ZSwiaWF0IjoxNzAzNzk2OTcyLCJleHAiOjE3MDM4MDA1NzJ9.fqTIV_6f7bnx70jqGkyyDwd0603SYKGL6KvkQNebIaA

{
    "content": "Soy Tostada, un gato blanco y negro, y no tan molesto como Flerken."
}

### Eliminar un post por id

DELETE http://localhost:3000/posts/659af7c5414ee76dba0bfdb7
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NTk2ZWZiMjBkY2M5M2MxYWUxMjcyNjEiLCJpc0FkbWluIjp0cnVlLCJpYXQiOjE3MDQ5MDg3MjksImV4cCI6MTcwNDkxMjMyOX0.ln9ocJbVvAILi-Qmov8gtiCzXc4TTsKtVLmNL0M33yA

### Obtener todos los posts de un autor

GET http://localhost:3000/posts/user/658d99d70d8cc33e9c252d18

### Search posts

GET http://localhost:3000/posts/search?q=tostada

### Filter posts by category and author

GET http://localhost:3000/posts/filter?author=6596f0a98fb58425f0f95f7d