### Crear un nuevo post


POST http://localhost:3000/posts
Content-Type: application/json

{
    "title": "Flerken y su nuevo amigo",
    "content": "Flerken nos presenta a su nuevo amigo, Tostada.",
    "categories": ["friendship", "animals"]
}



### Obtener todos los posts con paginación

GET http://localhost:3000/posts

### Obtener un post por id

GET http://localhost:3000/posts/658dc74e74722faf97232caa

### Actualizar un post por id

PATCH http://localhost:3000/posts/658de124c4efa6c2272858a7
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkFkbWluIiwic3ViIjoiNjU4ZDlhMTA3NjRiZDljNTg2MWMxNTZmIiwiaXNBZG1pbiI6dHJ1ZSwiaWF0IjoxNzAzNzk2OTcyLCJleHAiOjE3MDM4MDA1NzJ9.fqTIV_6f7bnx70jqGkyyDwd0603SYKGL6KvkQNebIaA

{
    "content": "Soy Tostada, un gato blanco y negro, y no tan molesto como Flerken."
}

### Eliminar un post por id

DELETE http://localhost:3000/posts/6596dca458ce2b4d044a0e55
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NTk2ZWZiMjBkY2M5M2MxYWUxMjcyNjEiLCJpc0FkbWluIjp0cnVlLCJpYXQiOjE3MDQzOTA1ODQsImV4cCI6MTcwNDM5NDE4NH0.kmJZhkh7S6NVJMX2SSDBnxqfX-A2Ftr0PstnOlQxe5s

### Obtener todos los posts de un autor

GET http://localhost:3000/posts/user/658d99d70d8cc33e9c252d18

### Search posts

GET http://localhost:3000/posts/search?q=tostada

### Filter posts by category and author

GET http://localhost:3000/posts/filter?author=6596f0a98fb58425f0f95f7d