### GET para traer los usuarios

GET http://localhost:3000/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NTk2ZWZiMjBkY2M5M2MxYWUxMjcyNjEiLCJpc0FkbWluIjp0cnVlLCJpYXQiOjE3MDQ5MTYzMTEsImV4cCI6MTcwNDkxOTkxMX0.ZpK0CQCAm8QYSYsm6wWssEHHJ-oDnZDZsLLpc0lyBK8

### Get usuario por ID

GET http://localhost:3000/users/6596ef30363eb2863c18dbd7
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NTk2ZWZiMjBkY2M5M2MxYWUxMjcyNjEiLCJpc0FkbWluIjp0cnVlLCJpYXQiOjE3MDQ5MDg3MjksImV4cCI6MTcwNDkxMjMyOX0.ln9ocJbVvAILi-Qmov8gtiCzXc4TTsKtVLmNL0M33yA


### Login de usuario admin

POST http://localhost:3000/users/login
Content-Type: application/json

{
    "username": "Admin",
    "password": "12341234"
}

### Login de usuario no admin

POST http://localhost:3000/users/login
Content-Type: application/json

{
    "username": "Mitski",
    "password": "12341234"
}

### POST para crear un usuario

POST http://localhost:3000/users
Content-Type: application/json

{
    "username": "Flerkeno",
    "email": "flerkeno@gmail.com",
    "password": "12341234"
}

### PATCH para actualizar un usuario

PATCH http://localhost:3000/users/6596e0438d611c20b195b65a
Content-Type: application/json
Authorization: Bearer
{
    "name": "Flerken",
    "email": "flerken@gmail.com"
}

### DELETE para borrar un usuario

DELETE http://localhost:3000/users/659ed8dc594e115ada6a8a5c
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NTk2ZWZiMjBkY2M5M2MxYWUxMjcyNjEiLCJpc0FkbWluIjp0cnVlLCJpYXQiOjE3MDQ5MDg3MjksImV4cCI6MTcwNDkxMjMyOX0.ln9ocJbVvAILi-Qmov8gtiCzXc4TTsKtVLmNL0M33yA
